remote_theme: github-profile-achievements/jekyll-theme

title: Pełna lista wszystkich osiągnięć i odznak Profilu GitHub
description: Pełna lista wszystkich osiągnięć i odznak Profilu GitHub
permalinks: pretty

lang: pl
logo_url: https://avatars.githubusercontent.com/u/117988194?s=200&v=4

# Navbar
navbar_link_text: Osiągnięcia Profilu GitHub w innych językach
navbar_button_text: Ta strona na GitHub
